2021-01-25 14:25:08,995 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-25 14:26:12,161 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-25 14:26:18,009 ERROR: Exception on /index [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/selman/Desktop/microblog/app/routes.py", line 101, in before_request
    g.locale = str(get_locale())
NameError: name 'get_locale' is not defined
2021-01-25 14:26:20,205 ERROR: Exception on /logout [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/selman/Desktop/microblog/app/routes.py", line 101, in before_request
    g.locale = str(get_locale())
NameError: name 'get_locale' is not defined
2021-01-25 14:26:22,235 ERROR: Exception on /logout [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/selman/Desktop/microblog/app/routes.py", line 101, in before_request
    g.locale = str(get_locale())
NameError: name 'get_locale' is not defined
2021-01-25 14:26:24,997 ERROR: Exception on /index [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/selman/Desktop/microblog/app/routes.py", line 101, in before_request
    g.locale = str(get_locale())
NameError: name 'get_locale' is not defined
2021-01-25 14:26:27,762 ERROR: Exception on / [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/selman/Desktop/microblog/app/routes.py", line 101, in before_request
    g.locale = str(get_locale())
NameError: name 'get_locale' is not defined
2021-01-25 14:26:48,424 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-25 14:30:56,313 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-25 15:40:45,641 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:77]
2021-01-25 15:40:48,504 ERROR: Exception on / [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1890]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/selman/Desktop/microblog/app/main/routes.py", line 20, in before_request
    g.locale = str(get_locale())
  File "/home/selman/.local/lib/python3.8/site-packages/flask_babel/__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "/home/selman/Desktop/microblog/app/__init__.py", line 84, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
KeyError: 'LANGUAGES'
2021-01-25 15:41:56,393 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:77]
