2021-01-22 15:51:48,911 ERROR: Exception on /user/as [GET] [in /home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/selmanbaskaya/Desktop/microblog/app/routes.py", line 93, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2021-01-22 15:52:11,443 ERROR: Exception on /user/a [GET] [in /home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/selmanbaskaya/Desktop/microblog/app/routes.py", line 93, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2021-01-22 15:52:16,861 ERROR: Exception on /user/asa [GET] [in /home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/selmanbaskaya/Desktop/microblog/app/routes.py", line 93, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2021-01-22 15:52:43,447 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 16:03:24,537 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:48]
2021-01-22 16:04:49,466 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:48]
2021-01-23 21:36:12,430 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-23 21:37:38,575 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-23 21:38:09,878 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-25 13:34:25,585 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:48]
2021-01-25 13:49:09,826 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
2021-01-25 13:51:42,269 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
2021-01-25 13:53:28,674 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
2021-01-25 13:53:40,707 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
2021-01-25 13:54:36,437 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
2021-01-25 13:57:30,571 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
2021-01-25 14:01:55,660 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
2021-01-25 14:02:07,423 INFO: Microblog startup [in /home/selman/Desktop/microblog/app/__init__.py:51]
